### ISSUE TITLE
Multi character control

### ISSUE THREAD

**Issue by Todozu** [tinybike/Brawl#1]
Hello. I know you`re making real-time battle mod for BG-3 and have some difficulties with how to control couple of characters at same time (Multi character control MCC). I'm not very experienced in programming, but I can offer an idea that you can use as a sample or a spark of inspiration. There's one rather old game "Granado espada", where this issue is resolved simply brilliantly. Probably it will help you.
With best wishes and respect, Todozu.

**Comment by tinybike** [comment]
Thanks very much for the suggestion!  I'd like to ultimately include some kind of simple AI for other party members (similar to how e.g. NWN does it for your follower), but for now if you want to run a full party by yourself you may have to just pause a lot.

**Comment by tinybike** [comment]
Update: I ended up implementing companion AI.  You can see an example of it in action [here](https://www.youtube.com/watch?v=q3lnl3lcDXg).
